define({
    "root": {
        "meIdentification": "GENERAL INFORMATION",
        "uid": "Resource identification code",
        "version": "Resource version",
        "language": "Language(s)",
        "languageDetails": "Language details",
        "title": "Title",
        "creationDate": "Creation date",
        "characterSet": "Character-set",
        "metadataStandardName": "Used metadata standards",
        "metadataStandardVersion": "Version of the metadata standards",
        "metadataLanguage": "Language(s) used for metadata",
        "contacts": "Contact(s)",
        "addContact": "Add a Contact",
        "addAnother": "Add Another",
        "remove": "Remove",
        "showAll": "Show All",
        "new": "NEW",
        "showAllContacts" : "Show All Contacts",
        "responsibleParty": "Responsible party",
        "organization": "Organization",
        "organizationUnit": "Organization unit/division",
        "pointOfContact": "Point of contact",
        "titleForenameSurname": "Title forename and surname",
        "position": "Position",
        "role": "Role",
        "specify": "Specify",
        "contactInfo": "Contact information",
        "provideAtLeastOne": "Must provide at least one of the following (phone, address, email)",
        "phone": "Telephone number",
        "address": "Address",
        "emailAddress": "Email address",
        "hoursOfService": "Hours of service",
        "contactInstruction": "Instruction",
        "noDataValue": "Value assigned to No-data",
        "meContent": "LIVESTOCK POPULATION",
        "resourceRepresentationType": "Type of resource",
        "keywords": "Keywords",
        "typeThenEnter": "Type then press Enter",
        "description": "Abstract",
        "statisticalConceptsDefinitions": "Statistical concepts/definitions",
        "seReferencePopulation": "Reference Population",
        "statisticalPopulation": "Statistical population",
        "statisticalUnit": "Statistical unit",
        "referencePeriod": "Period of reference",
        "referenceArea": "Area of reference",
        "seCoverage": "Coverage",
        "coverageSectors": "Main sector(s) (coded)",
        "coverageSectorsDetails": "Main sector(s)",
        "coverageTime": "Coverage time",
        "coverageGeographic": "Geographic extent",
        "seCodeList": "Codelist",
        "numberOfLevels": "Number of levels",
        "typeOfCodeList": "Type of codelist",
        "meInstitutionalMandate": "ANIMAL IDENTIFICATION",
        "legalActsAgreements": "Legal acts/agreements",
        "institutionalMandateDataSharing": "Data sharing arrangements",
        "meStatisticalProcessing": "Statistical Processing",
        "sePrimaryDataCollection": "Primary Data Collection",
        "dataCollector": "Data collector",
        "typeOfCollection": "Type of collection",
        "samplingProcedure": "Sampling procedure",
        "dataCollection": "Data collection",
        "collectionPeriodicity": "Periodicity of data collection",
        "seSecondaryDataCollection": "Secondary Data Collection",
        "originOfCollectedData": "Origin of collected data",
        "onlyRequiredIfOtherIOsSelected": "Only required if 'Other IOs' selected above",
        "rawDataDescription": "Description of raw data",
        "seDataCompilation": "Data Compilation",
        "missingData": "Missing data",
        "weights": "Weights",
        "aggregationProcessing": "Process of aggregation",
        "aggregationFormula": "Aggregation formula",
        "dataAdjustment": "Process of adjustment",
        "dataAdjustmentDetails": "Details on process of adjustment",
        "indexType": "Type of index",
        "basePeriod": "Base period",
        "seDataValidation": "Data Validation",
        "dataValidationIntermediate": "Data validation - intermediate",
        "dataValidationOutput": "Data validation - output",
        "dataValidationSource": "Data validation - source",
        "meDataQuality": "Data Quality",
        "qualityManagement": "Quality management",
        "qualityAssessment": "Data quality assessment",
        "qualityAssurance": "Quality assurance",
        "seAccuracy": "Accuracy",
        "accuracyNonSampling": "Accuracy - non sampling error",
        "accuracySampling": "Accuracy - sampling error",
        "seDataRevision": "Data Revision",
        "revisionPolicy": "Revision policy",
        "revisionPractice": "Data revision practice",
        "seRelevance": "Relevance",
        "userNeeds": "User needs",
        "userSatisfaction": "User satisfaction",
        "completeness": "Completeness",
        "completenessPercentage": "Percentage of completeness",
        "seComparability": "Comparability Coherence",
        "comparabilityGeographical": "Geographic comparability",
        "comparabilityTime": "Time comparability",
        "coherenceIntern": "Internal coherence",
        "seTimelinessPunctuality": "Timeliness and Punctuality",
        "timeliness": "Timeliness",
        "punctuality": "Punctuality",
        "meAccessibility": "Accessibility",
        "seDataDissemination": "Data Dissemination",
        "seDistribution": "Distribution",
        "nonRestrictedResourcesOnly": "Can be completed for non-restricted resources only",
        "onlineResource": "Link to the on-line resource",
        "disseminationFormat": "Dissemination formats",
        "seReleasePolicy": "Release Policy",
        "releaseCalendar": "Release calendar",
        "releaseCalendarAccess": "Access to the release calendar",
        "disseminationPeriodicity": "Dissemination periodicity",
        "embargoTime": "Embargo time",
        "clickToShowCalendar": "Click to show calendar",
        "clarity": "Clarity",
        "metadataCompletenessRate": "Metadata completeness rate",
        "seConfidentiality": "Confidentiality",
        "confidentialityPolicy": "Confidentiality - Policy",
        "confidentialityDataTreatment": "Confidentiality - Data treatment",
        "confidentialityStatus": "Status of confidentiality",
        "meMaintenance": "Maintenance",
        "maintenanceAgency": "Maintenance agency",
        "seUpdate": "Update",
        "updateDate": "Last update date",
        "updatePeriodicity": "Frequency of update",
        "seMetadataMaintenance": "Metadata Maintenance",
        "metadataLastCertified": "Metadata last certified",
        "metadataLastPosted": "Metadata last posted",
        "metadataLastUpdate": "Metadata last update",
        "meDocuments": "Documents",
        "document": "Documents linked to the data",
        "citationDoc": "Citation",
        "citationDocTitle": "Title",
        "documentKind": "Kind of document",
        "date": "Date",
        "contact": "Contact",
        "documentLink": "Document hyperlink",
        "notes": "Notes",
        "isbn": "ISBN code",
        "issn": "ISSN code",
        "referenceEntity": "Select a reference subject",
        "referenceElement": "Select a reference element",
        "meSpatialRepresentation": "Spatial Representation",
        "layerType": "Type of layer",
        "typeOfProduct": "Type of product",
        "seBoundingBox": "Bounding Box",
        "xMin": "West bound longitude",
        "xMax": "East bound longitude",
        "yMin": "South bound latitude",
        "yMax": "North bound latitude",
        "seGridSpatialRepresentation": "Grid Spatial Representation",
        "numberOfDimensions": "Number of dimensions",
        "axisDimensionProperties": "Information about spatial-temporal axis properties",
        "axis": "Axis",
        "axisName": "Name of axis",
        "axisSize": "Axis size",
        "resolution": "Resolution",
        "extent": "Extent",
        "composedMU": "Composed unit of measurement",
        "composed": "Composed",
        "simple": "Simple",
        "measurementSystem": "Measurement system",
        "nameMU": "Measurement unit name",
        "conversionToStandard": "Conversion to the standard",
        "cellGeometry": "Identification of grid data as point or cell",
        "cellOfOrigin": "Origin of raster cell",
        "xyPosition": "Coordinate of the origin within the cell",
        "seVectorSpatialRepresentation": "Vector Spatial Representation",
        "topologyLevel": "Degree of complexity of the spatial relationships",
        "geometricObjects": "Geometric object",
        "meReferenceSystem": "Reference System Information",
        "referenceSystemIdentifier": "Identifier of reference system",
        "referenceSystemName": "Extended name of reference system",
        "referenceSystemAuthority": "Reference system authority",
        "projection": "Projection",
        "projectionName": "Name of projection",
        "seProjectionParameters": "Projection Parameters",
        "zone": "Zone",
        "standardParallel": "Standard parallel",
        "longitudeOfCentralMeridian": "Longitude of central meridian",
        "latitudeOfProjectionOrigin": "Latitude of projection origin",
        "falseEasting": "False easting",
        "falseNorthing": "False northing",
        "falseEastingNorthingUnits": "Unit of measure of false easting/northing",
        "scaleFactorAtEquator": "Scale factor at the equator",
        "heightOfProspectivePointAboveSurface": "Height of view point above the Earth (m)",
        "longitudeOfProjectionCenter": "Longitude of projection centre",
        "latitudeOfProjectionCenter": "Latitude of projection center",
        "scaleFactorAtCenterLine": "Scale factor at center line",
        "straightVerticalLongitudeFromPole": "Straight vertical longitude from pole",
        "scaleFactorAtProjectionOrigin": "Scale factor at projection origin",
        "seObliqueLineAzimuth": "Oblique Line Azimuth",
        "azimuthAngle": "Azimuth angle",
        "azimuthMeasurePointLongitude": "Longitude of the map projection origin",
        "seObliqueLinePoint": "Oblique Line Point",
        "obliqueLineLatitude": "Oblique line latitude",
        "obliqueLineLongitude": "Oblique line longitude",
        "ellipsoid": "Ellipsoid",
        "ellipsoidName": "Name of ellipsoid",
        "seEllipsoidParameters": "Ellipsoid Parameters",
        "semiMajorAxis": "Semi major axis",
        "axisUnits": "Semi-major axis unit of measure",
        "denominatorOfFlatteningRatio": "Denominator of flattening rate",
        "datum": "Datum",
        "datumName": "Name of datum"
    },
    "fr": true
});