define({
    "root": {
        "uid": "It is a code that identifies the resource the metadata is associated to.",
        "version": "For some kinds of resources the version may be necessary to uniquely identify it.",
        "language": "Language used by the resource for textual information.",
        "languageDetails": "Comments and additional details about the language used for the textual information of the resource.",
        "titleResource": "Label used as the resource title.",
        "creationDate": "Creation date of the resource.",
        "characterSet": "Character encoding standard used by the resource.",
        "metadataStandardName": "Name of the metadata standard specifications used.",
        "metadataStandardVersion": "Version of the metadata standard specifications used.",
        "metadataLanguage": "Language(s) used to compile the metadata record.",
        "contacts": "Party(ies) playing different roles in respect to the resource, and in particular the party responsible for the resource.",
        "organizationResponsible": "Name of the responsible organization.",
        "organizationUnit": "Addressable subdivision of an organization.",
        "pointOfContact": "Responsible person - title, given name and surname",
        "position": "Role or position of the responsible person",
        "role": "Function performed by the responsible party concerning the resource.",
        "specify": "Specify the role performed by the responsible party.",
        "hoursOfService": "Time period (including time zone) when the organization/individual can be contacted.",
        "contactInstruction": "Supplemental instructions on how or when to contact the individual or organization.",
        "noDataValue": "Value assigned to the cells to represent the absence of data.",
        "resourceRepresentationType": "Typology of the resource the metadata refers to.",
        "keywords": "Commonly used word(s), formalized word(s) or phrase(s) used to describe the resource.",
        "seReferencePopulation": "Information on the statistical population the resource refers to.",
        "statisticalPopulation": "Target statistical population (one or more) the resource refers to.",
        "statisticalUnit": "Simplest unit for which information is sought and for which statistics are ultimately compiled.",
        "referencePeriod": "Specific time periods the statistical variables refer to.",
        "coverageSectors": "Sector(s) the resource refers to as specified in the selected codelist.",
        "coverageTime": "Information about the time period for which data are available.",
        "seCodeList": "Information related to the resource 'codelist'.",
        "numberOfLevels": "Hierarchical codelists may have several levels, information about the number of levels must be reported in order to describe the hierarchy of the codelist.",
        "typeOfCodeList": "Codelist typology.",
        "legalActsAgreements": "Legal acts or other formal or informal agreements that assign responsibility as well as authority to an agency for the collection, processing, and dissemination of the resource.",
        "institutionalMandateDataSharing": "Arrangements or procedures for data sharing and coordination.",
        "sePrimaryDataCollection": "Describes the procedures used to collect data obtained directly from first-hand sources by means of surveys, observation or experimentation.",
        "dataCollector": "The entity (individual, agency or institution) responsible for administering the questionnaire or interview for compiling the data.",
        "typeOfCollection": "Coded element which specifies the type of data collection method (e.g. census, random sampling, etc.).",
        "samplingProcedure": "The type of sample design used to select the survey respondents to represent the population. It may refer to information on sample design, sample size, sample frame, sample updating etc.",
        "collectionPeriodicity": "Frequency with which the data are collected from the sources.",
        "seSecondaryDataCollection": "Is filled when the agency compiling and publishing data does not coincide with the entity (subject, agency or institution) who has conducted the procedure of collecting data. It reports information about the source that have already collected data.",
        "originOfCollectedData": "Coded element which allows to specify in a standard way the origin of the resource.",
        "seSecondaryDataCollectionOrganization": "Please specify the exact source of the resource.",
        "rawDataDescription": "Description of raw data",
        "dataCollection" : "Data collection details",
        "seDataCompilation": "Includes many aspects (e.g. data editing, imputation, weighting, adjustment for non-response, calibration, model used etc.) concerning the operations on data.",
        "missingData": "It describes under which circumstances missing data are estimated or imputed and when the cells are left empty. It also describes the methodologies used to estimate/impute missing values.",
        "weights": "Description of weights applied to sampling procedures in order to produce accurate statistical results. This field reports the criteria for using weights in analysis of collection, the formulas and coefficients developed and how they are applied to data.",
        "aggregationProcessing": "Information about the methodology used to aggregate data.",
        "aggregationFormula": "Formula used to aggregate data.",
        "dataAdjustment": "Type of adjustment used represented by a code.",
        "dataAdjustmentDetails": "Set of procedures employed to modify statistical data to enable it to conform with national or international standards (such as seasonal adjustment methods, time series decomposition, or other similar methods).",
        "indexType": "Type of index number used in the statistical production process.",
        "basePeriod": "Period of time used as a base of an index number or to which a time series refers (e.g. base year 2000 for certain annual data).",
        "seDataValidation": "Methods and processes for assessing statistical data. It describes the process of monitoring data compilation progress and ensuring the quality of the statistical results.",
        "dataValidationIntermediate": "Assessment of the quality and correctness of intermediate calculations leading to statistical outputs.",
        "dataValidationOutput": "Assessment of discrepancies and/or inaccuracies observed in the statistical outputs.",
        "dataValidationSource": "Assessment of discrepancies and/or inaccuracies inherent to the data source.",
        "qualityManagement": "Structure, responsibilities and procedures established for guaranteeing the quality of the data.",
        "qualityAssessment": "Overall qualitative assessment of the quality of the statistical outputs.",
        "qualityAssurance": "Description of the process assuring that the data production processes conforms to the statistical quality standards.",
        "seDataRevision": "Describes the policy and practice for identifying the revision status of the data, as well as the availability of revision studies and analysis.",
        "revisionPolicy": "Policy concerning the periodically revision of the resource and ensuring the transparency of disseminated data.",
        "seRelevance": "Evaluation of data-quality through user satisfaction involving also information about the resource-completeness.",
        "userNeeds": "Classification of user needs with some indication of their importance, the uses for which they want the statistical outputs and those given special consideration. Unmet user needs and the reasons for not meeting them should be included as well.",
        "userSatisfaction": "How the views and opinions of the users are collected. In addition, the main results regarding the user satisfaction should be shown (in the form of a user satisfaction index if available) and the date of the most recent user satisfaction survey.",
        "completeness": "State of completeness of the resource.",
        "completenessPercentage": "Percentage of the state of completeness of the resource.",
        "comparabilityGeographical": "Degree of data comparability across the geographic areas or regions referenced by the resource. Data might be derived from surveys that in general are conducted by different statistical agencies. These surveys often refer to populations of different geographical areas, sometimes based on different methodologies.",
        "comparabilityTime": "Extent to which data are comparable or reconcilable over time. It refers to the degree of comparability between the measures of a time series (e.g. related to a country, a commodity and a variable) included in the resource.",
        "coherenceIntern": "General estimate of the extent to which data are consistent within the resource.",
        "timeliness": "It refers to the speed of data availability, length of time between data availability and the event or phenomenon they describe.",
        "punctuality": "Time lag between the release date of data and the target date announced in some official release calendar.",
        "seDistribution": "Provides information on how to access the resource and indicates the supported formats.",
        "onlineResource": "Link to the on-line resource",
        "disseminationFormat": "Formats available for downloading the resources (e.g. excel, csv, pdf, etc.).",
        "seReleasePolicy": "Regulations used to determine the mode of distribution of the resource.",
        "releaseCalendar": "Policy regarding the release of the resource in accordance with the pre-announced schedule. It also provides information on the availability of the release calendar.",
        "releaseCalendarAccess": "Link or references to the release calendar.",
        "disseminationPeriodicity": "Frequency of data dissemination (e.g. daily, monthly, quarterly, yearly).",
        "embargoTime": "Time span between the completion of the production process of statistical data and their publication.",
        "seClarity": "Gives information about the availability of additional information (documentation, metadata ...) linked to the resource.",
        "clarity": "Extent to which easily comprehensible metadata are available. It indicates whether a resource is accompanied by appropriate metadata and other relevant documentation.",
        "metadataCompletenessRate": "The percentage of completeness of metadata offers a numerical evaluation of the extent to which the resource is documented.",
        "confidentialityPolicy": "Legislative measures or other formal procedures which prevent unauthorized disclosure of data that identify a person or economic entity either directly or indirectly. It consists of a textual description and references to legislation or other rules related to statistical confidentiality.",
        "confidentialityDataTreatment": "Rules applied for treating the resource to ensure confidentiality and prevent unauthorized disclosure.",
        "confidentialityStatus": "Coded information describing the degree of confidentiality of the resource.",
        "maintenanceAgency": "Organization or other expert body that maintains the resource.",
        "seUpdate": "Maintenance operations concern the periodic update of the resource.",
        "updateDate": "Last physical update date.",
        "updatePeriodicity": "Frequency of update",
        "seMetadataMaintenance": "Maintenance operations include the periodic update of metadata to ensure that the resource is properly described.",
        "metadataLastCertified": "Latest date of certification of the metadata.",
        "metadataLastPosted": "Latest date of publication of the metadata. It is usually automatically updated by the metadata production system.",
        "metadataLastUpdate": "Most recent date of update of the metadata.",
        "document": "Regular or ad-hoc publications linked to the resource.",
        "citationDocTitle": "Title by which the cited resource is known which offers a quick information about its content.",
        "documentKind": "Kind of resource attached to data.",
        "citationDate": "Reference date for the cited document.",
        "contact": "Name and position information for an individual or organization that is responsible for the resource.",
        "documentLink": "Web site link allowing the user access to the information resource.",
        "notes": "Some additional details about the resource mainly concerning the domain to which the resource refers.",
        "isbn": "If available, the International Standard Book Number can be reported in order to uniquely identify the resource cited.",
        "issn": "If available, the International Standard Serial Number (used to identify periodical publications such as reviews and scientific journals) can be reported in order to uniquely identify the resource cited.",
        "referenceEntity": "The metadata entity(ies) the document refers to. This element allows users to contextualize the document by making reference to specific metadata areas.",
        "referenceElement": "The metadata element(s)the document refers to. This element allows users to contextualize the document by making reference to specific metadata element(s).",
        "layerType": "Layer typology: vector or raster spatial representation.",
        "typeOfProduct": "Coded information about the product managed.",
        "seBoundingBox": "Includes the planar measurement units used to express the X,Y values. The bounding box indicates the smaller quadrilateral shape that includes all features of the considered resource.",
        "xMin": "The smaller X coordinate value delimiting the resource",
        "xMax": "The higher X coordinate value delimiting the resource",
        "yMin": "The smaller Y coordinate value delimiting the resource",
        "yMax": "The higher Y coordinate value delimiting the resource",
        "seGridSpatialRepresentation": "Parameters about a grid (raster) resource. The SE Grid SpatialRepresentation entity refers to a raster whose cells are regularly distributed in the space.",
        "numberOfDimensions": "Number of independent spatial-temporal axes. For example, a grid dataset representing the topography of an area has 3 dimensions: x, y for the planar representation of the area and z reporting the elevation value of each cell.",
        "axisDimensionProperties": "Information about the spatial-temporal axis properties.",
        "axisName": "Name of axis",
        "axisSize": "Number of elements along the axis.",
        "resolution": "Degree of detail in the grid dataset.",
        "extent": "Description of the type of magnitude which has been measured (e.g. a length, an area, a volume).",
        "composedMU": "Since a wide variety of phenomenon is measured combining several simple unit of measure, it is requested a Boolean element indicating whether simple or composed unit of measure is used.",
        "measurementSystem": "System devised to measure some physical quantity (such distance or area...). Examples are the English System of feet and inches or the metric system of millimetres, centimetres and meters, also the System International (SI) System of Units",
        "nameMU": "Name of the simple/composed unit of measure adopted.",
        "conversionToStandard": "Allows to convert the unit of measure used in a standard measurement system.",
        "cellGeometry": "Specifies whether each pixel of the raster data represents a point or an area. A raster with the cell geometry as point assumes that the features to represent, or the values to report, refers to the center of the cell; cell geometry as area represents the whole area covered by the cell (e.g. averages of values falling within the cell; dominant feature of the cell, etc.).",
        "cellOfOrigin": "Origin of the raster is the lower left or the upper left cell.",
        "xyPosition": "Whether coordinates of the origin of the raster refer to the center or the corner of the cell of origin.",
        "seVectorSpatialRepresentation": "Information about the vector spatial objects in the dataset.",
        "topologyLevel": "Degree of complexity of the spatial relationships expressed through a code list.",
        "geometricObjects": "Information about the geometric objects used in the dataset (e.g. point, line, polygon, etc.).",
        "referenceSystemIdentifier": "Identifier of the reference system. One of the most common standards for reference systems is the EPSG Geodetic Parameter Registry, created by the European Petroleum Survey Group.",
        "referenceSystemName": "Alias or the name of the reference system.",
        "referenceSystemAuthority": "Details on the authority linked to the reference system.",
        "seProjection": "Provides the identifiers of the projection of the considered Coordinate Reference System (CRS).",
        "projection": "Identifier of the projection used.",
        "projectionName": "Name of the projection used.",
        "seProjectionParameters": "Contains the set of parameters that describe the projection.",
        "zone": "Unique identifier for 100,000-meter grid zone.",
        "standardParallel": "Line of constant latitude where the projection surface intersects the earth.",
        "longitudeOfCentralMeridian": "Line of longitude at the center of a map projection generally used as the basis for constructing the projection.",
        "latitudeOfProjectionOrigin": "Latitude chosen as the origin of the coordinates for a map projection.",
        "falseEasting": "Value added to all 'x' values to the coordinates for a map projection. It is expressed in the unit of measure identified in Planar Coordinate Unit.",
        "falseNorthing": "Value added to all 'y' values to the coordinates for a map projection. This value frequently is assigned to eliminate negative numbers. It is expressed in the unit of measure identified in Planar Coordinates Units.",
        "falseEastingNorthingUnits": "Unit of the false easting and false northing.",
        "scaleFactorAtEquator": "Ratio between the distance on earth and the corresponding map distance, along the equator.",
        "heightOfProspectivePointAboveSurface": "Height of viewpoint above the Earth expressed in meters.",
        "longitudeOfProjectionCenter": "Longitude of the point of projection for azimuthal projections.",
        "latitudeOfProjectionCenter": "Latitude of the point of projection for azimuthal projections.",
        "scaleFactorAtCenterLine": "Ratio between distance on earth and the corresponding map distance, along the center line.",
        "straightVerticalLongitudeFromPole": "Longitude to be oriented straight up from the North Pole.",
        "scaleFactorAtProjectionOrigin": "Multiplier for reducing a distance obtained from a map by computation or scaling to the actual distance at the projection origin.",
        "seObliqueLineAzimuth": "Method used to describe the line along which an oblique Mercator map projection is centred using the map projection origin and an azimuth.",
        "azimuthAngle": "Measure clockwise from north and express in degree of the angle.",
        "azimuthMeasurePointLongitude": "Longitude of the origin in the map projection.",
        "seObliqueLinePoint": "Method used to describe the line along which an oblique mercator map projection is centred using two points near the limit of the mapped region that define the centre line.",
        "obliqueLineLatitude": "Latitude of a point defining the oblique line.",
        "obliqueLineLongitude": "Longitude of a point defining the oblique line.",
        "seEllipsoid": "Provides the identififers of the ellipsoid of the considered Coordinate Reference System (CRS).",
        "ellipsoid": "Identifier of the ellipsoid used.",
        "ellipsoidName": "Name of the ellipsoid used.",
        "seEllipsoidParameters": "Set of parameters that describe the ellipsoid.",
        "semiMajorAxis": "Measure of the equatorial axis of the ellipsoid.",
        "axisUnits": "Units of the semi-major axis.",
        "seDatum": "Provides the identifiers of the datum of the considered Coordinate Reference System (CRS).",
        "datumName": "Name of the datum used."
    },
    "fr": true
});