define({
	"fr": false,
	"root": {
		"error_notset":"Property must be set",
		"error_notempty":"Value required",
		"error_enum":"Value must be one of the enumerated values",
		"error_anyOf":"Value must validate against at least one of the provided schemas",
		"error_oneOf":"Value must validate against exactly one of the provided schemas. It currently validates against {{0}} of the schemas.",
		"error_not":"Value must not validate against the provided schema",
		"error_type_union":"Value must be one of the provided types",
		"error_type":"Value must be of type {{0}}",
		"error_disallow_union":"Value must not be one of the provided disallowed types",
		"error_disallow":"Value must not be of type {{0}}",
		"error_multipleOf":"Value must be a multiple of {{0}}",
		"error_maximum_excl":"Value must be less than {{0}}",
		"error_maximum_incl":"Value must at most {{0}}",
		"error_minimum_excl":"Value must be greater than {{0}}",
		"error_minimum_incl":"Value must be at least {{0}}",
		"error_maxLength":"Value must be at most {{0}} characters long",
		"error_minLength":"Value must be at least {{0}} characters long",
		"error_pattern":"Value must match the provided pattern",
		"error_additionalItems":"No additional items allowed in this array",
		"error_maxItems":"Value must have at most {{0}} items",
		"error_minItems":"Value must have at least {{0}} items",
		"error_uniqueItems":"Array must have unique items",
		"error_maxProperties":"Object must have at most {{0}} properties",
		"error_minProperties":"Object must have at least {{0}} properties",
		"error_required":"Object is missing the required property '{{0}}'",
		"error_additional_properties":"No additional properties allowed, but property {{0}} is set",
		"error_dependency":"Must have property {{0}}"
	}
});